import { useState, useCallback, useMemo, useRef } from "react";

var VAT=0.05,SPF_ER=0.1175,SPF_EE=0.07,SPF_GV=0.0525;
var TARGETS={"IT & Telecom":25,Banking:90,Retail:20,Tourism:30,Construction:15,Manufacturing:20,Education:50,Healthcare:40,"Oil & Gas":60,Transport:30,"General Trading":15};
var DEPTS=Object.keys(TARGETS);

var initEmp=[
  {id:1,name:"أحمد الحارثي",nameEn:"Ahmed Al-Harthi",nat:"Omani",dept:"IT & Telecom",salary:850,allow:150,roleEn:"Software Dev",join:"2024-01-15",spf:"SPF-001",email:"ahmed@co.om",bank:"Bank Muscat",iban:"OM12BMCT001"},
  {id:2,name:"فاطمة البلوشي",nameEn:"Fatma Al-Balushi",nat:"Omani",dept:"IT & Telecom",salary:750,allow:120,roleEn:"Systems Analyst",join:"2024-03-01",spf:"SPF-002",email:"fatma@co.om",bank:"Bank Muscat",iban:"OM12BMCT002"},
  {id:3,name:"راجيش كومار",nameEn:"Rajesh Kumar",nat:"Indian",dept:"IT & Telecom",salary:500,allow:80,roleEn:"Support Tech",join:"2023-11-10",spf:"—",email:"rajesh@co.om",bank:"NBO",iban:"OM12NBO003"},
  {id:4,name:"سعيد الريامي",nameEn:"Saeed Al-Riyami",nat:"Omani",dept:"Retail",salary:600,allow:100,roleEn:"Sales Manager",join:"2023-06-20",spf:"SPF-003",email:"saeed@co.om",bank:"Bank Dhofar",iban:"OM12BD004"},
  {id:5,name:"محمد علي",nameEn:"Mohammad Ali",nat:"Pakistani",dept:"Retail",salary:350,allow:50,roleEn:"Salesperson",join:"2024-02-15",spf:"—",email:"mohammad@co.om",bank:"Alizz",iban:"OM12AL005"},
  {id:6,name:"مريم الكندي",nameEn:"Maryam Al-Kindi",nat:"Omani",dept:"Retail",salary:550,allow:90,roleEn:"Accountant",join:"2024-04-01",spf:"SPF-004",email:"maryam@co.om",bank:"Bank Muscat",iban:"OM12BMCT006"},
  {id:7,name:"خالد المعمري",nameEn:"Khalid Al-Mamari",nat:"Omani",dept:"Construction",salary:700,allow:130,roleEn:"Civil Engineer",join:"2023-09-01",spf:"SPF-005",email:"khalid@co.om",bank:"Sohar",iban:"OM12SI007"},
  {id:8,name:"سانجاي باتيل",nameEn:"Sanjay Patel",nat:"Indian",dept:"Construction",salary:300,allow:40,roleEn:"Site Supervisor",join:"2024-05-01",spf:"—",email:"sanjay@co.om",bank:"NBO",iban:"OM12NBO008"},
];
var initInv=[
  {id:"INV-001",client:"شركة عمان للتقنية",clientEn:"Oman Tech Co.",date:"2025-03-01",due:"2025-03-31",items:[{desc:"استشارات",descEn:"Consulting",qty:1,price:2500}],status:"paid",cur:"OMR",notes:""},
  {id:"INV-002",client:"مؤسسة الخليج",clientEn:"Gulf Trading",date:"2025-03-10",due:"2025-04-10",items:[{desc:"تطوير موقع",descEn:"Website Dev",qty:1,price:1800},{desc:"استضافة",descEn:"Hosting",qty:1,price:200}],status:"pending",cur:"OMR",notes:""},
  {id:"INV-003",client:"فندق مسقط",clientEn:"Grand Muscat Hotel",date:"2025-02-15",due:"2025-03-15",items:[{desc:"نظام حجوزات",descEn:"Booking System",qty:1,price:3500}],status:"overdue",cur:"OMR",notes:""},
  {id:"INV-004",client:"ظفار للسياحة",clientEn:"Dhofar Tourism",date:"2025-01-20",due:"2025-02-20",items:[{desc:"تطبيق جوال",descEn:"Mobile App",qty:1,price:4200},{desc:"صيانة",descEn:"Maintenance",qty:3,price:150}],status:"paid",cur:"OMR",notes:""},
];
var initExp=[
  {id:1,descEn:"Rent",amount:800,date:"2025-03-01",cat:"rent",vatI:false,vendor:"الشموخ"},
  {id:2,descEn:"Electricity",amount:120,date:"2025-03-05",cat:"utilities",vatI:true,vendor:"مزون"},
  {id:3,descEn:"Office Supplies",amount:85,date:"2025-03-08",cat:"supplies",vatI:true,vendor:"مكتبة الجيل"},
  {id:4,descEn:"Internet",amount:45,date:"2025-03-10",cat:"utilities",vatI:true,vendor:"عمانتل"},
  {id:5,descEn:"Insurance",amount:350,date:"2025-03-12",cat:"insurance",vatI:false,vendor:"التأمين الوطني"},
];

function fmt(n,c){c=c||"OMR";var v=typeof n==="number"?n:0;var s={OMR:" ر.ع",AED:" د.إ",SAR:" ر.س"};return(c==="USD"?"$":"")+v.toFixed(c==="OMR"?3:2)+(s[c]||"");}
function fD(d){return new Date(d).toLocaleDateString("en-GB",{year:"numeric",month:"short",day:"numeric"});}
function iTotal(inv){var s=0;for(var i=0;i<inv.items.length;i++)s+=inv.items[i].qty*inv.items[i].price;return s;}
function iVat(inv){return iTotal(inv)*VAT;}
function iGrand(inv){return iTotal(inv)*(1+VAT);}
function today(){return new Date().toISOString().slice(0,10);}
function uid(){return Math.random().toString(36).slice(2,8);}
function maxId(arr){var m=0;for(var i=0;i<arr.length;i++){if(arr[i].id>m)m=arr[i].id;}return m;}

/* ── Build CSV/JSON strings ── */
function buildCSV(headers,rows){
  var lines=[headers.join(",")];
  for(var i=0;i<rows.length;i++){var cells=[];for(var j=0;j<rows[i].length;j++)cells.push('"'+String(rows[i][j]).replace(/"/g,'""')+'"');lines.push(cells.join(","));}
  return lines.join("\n");
}
function buildJSON(data){return JSON.stringify(data,null,2);}

/* ── Download via data URI (sandbox-safe, no Blob needed) ── */
function triggerDownload(filename,content,mime){
  try{
    var uri="data:"+mime+";charset=utf-8,"+encodeURIComponent(content);
    var a=document.createElement("a");
    a.href=uri;
    a.download=filename;
    a.style.display="none";
    document.body.appendChild(a);
    a.click();
    setTimeout(function(){document.body.removeChild(a);},100);
    return true;
  }catch(e){return false;}
}

function Ic(p){return <svg width={p.s||18} height={p.s||18} viewBox="0 0 24 24" fill="none" stroke={p.c||"currentColor"} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={p.d}/></svg>;}
var icons={home:"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10",file:"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z M14 2v6h6 M16 13H8 M16 17H8",users:"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2 M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M23 21v-2a4 4 0 0 0-3-3.87",dollar:"M12 1v22 M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6",shield:"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z",flag:"M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z M4 22v-7",gear:"M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33",plus:"M12 5v14 M5 12h14",check:"M20 6L9 17l-5-5",x:"M18 6L6 18 M6 6l12 12",search:"M11 17.25a6.25 6.25 0 1 1 0-12.5 6.25 6.25 0 0 1 0 12.5z M16.5 16.5L21 21",dl:"M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4 M7 10l5 5 5-5 M12 15V3",alert:"M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z M12 9v4 M12 17h.01",globe:"M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10z M2 12h20",wallet:"M20 12V8H6a2 2 0 0 1-2-2c0-1.1.9-2 2-2h12v4 M4 6v12a2 2 0 0 0 2 2h14v-4 M18 12a2 2 0 0 0 0 4h4v-4z",chart:"M18 20V10 M12 20V4 M6 20v-6",bell:"M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9 M13.73 21a2 2 0 0 1-3.46 0",edit:"M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7 M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z",trash:"M3 6h18 M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2",copy:"M20 9h-9a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2-2v-9a2 2 0 0 0-2-2z M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1",send:"M22 2L11 13 M22 2l-7 20-4-9-9-4 20-7z",eye:"M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z M12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z",menu:"M3 12h18M3 6h18M3 18h18",card:"M21 4H3a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h18a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2z M1 10h22",pie:"M21.21 15.89A10 10 0 1 1 8 2.83 M22 12A10 10 0 0 0 12 2v10z",print:"M6 9V2h12v7 M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2 M6 14h12v8H6z",clip:"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2 M9 2h6v4H9z"};

var C={bg:"#060b16",bg2:"#0c1222",card:"#111827",hov:"#162036",inp:"#0b1120",brd:"#1c2842",txt:"#e4e8f0",mut:"#7b879e",dim:"#4a5568",acc:"#c44530",accL:"#e06040",accG:"rgba(196,69,48,0.12)",g:"#10b981",gB:"rgba(16,185,129,0.08)",gD:"rgba(16,185,129,0.25)",y:"#eab308",yB:"rgba(234,179,8,0.08)",yD:"rgba(234,179,8,0.25)",r:"#ef4444",rB:"rgba(239,68,68,0.08)",rD:"rgba(239,68,68,0.25)",b:"#3b82f6",bB:"rgba(59,130,246,0.08)",bD:"rgba(59,130,246,0.25)",gld:"#d4a74a"};

function Badge(p){var cc={g:C.g,y:C.y,r:C.r,b:C.b};var bg={g:C.gB,y:C.yB,r:C.rB,b:C.bB};var bd={g:C.gD,y:C.yD,r:C.rD,b:C.bD};var col=p.color||"g";return <span style={{display:"inline-flex",alignItems:"center",padding:"2px 10px",borderRadius:20,fontSize:11,fontWeight:600,color:cc[col]||col,background:bg[col]||"rgba(255,255,255,.05)",border:"1px solid "+(bd[col]||"rgba(255,255,255,.1)")}}>{p.children}</span>;}
function Btn(p){var styles={primary:{background:C.acc,color:"#fff",border:"none"},secondary:{background:C.hov,color:C.txt,border:"1px solid "+C.brd},ghost:{background:"transparent",color:C.mut,border:"none"},success:{background:C.g,color:"#fff",border:"none"},danger:{background:C.r,color:"#fff",border:"none"}};var v=styles[p.v||"primary"];var sz=p.s==="sm"?{padding:"5px 11px",fontSize:11}:{padding:"8px 16px",fontSize:13};return <button type="button" onClick={p.disabled?undefined:p.onClick} style={Object.assign({},{borderRadius:8,fontWeight:600,cursor:p.disabled?"not-allowed":"pointer",display:"inline-flex",alignItems:"center",gap:6,fontFamily:"inherit",opacity:p.disabled?0.5:1},v,sz,p.style||{})}>{p.children}</button>;}
function Inp(p){return <div style={Object.assign({display:"flex",flexDirection:"column",gap:4},p.style||{})}>{p.label&&<label style={{fontSize:11,fontWeight:600,color:C.mut,textTransform:"uppercase",letterSpacing:".04em"}}>{p.label}</label>}<input type={p.type||"text"} value={p.value} onChange={function(e){p.onChange(e.target.value);}} placeholder={p.placeholder||""} style={{padding:"8px 12px",background:C.inp,border:"1px solid "+C.brd,borderRadius:8,color:C.txt,fontSize:13,fontFamily:"inherit",outline:"none"}}/></div>;}
function Sel(p){return <div style={Object.assign({display:"flex",flexDirection:"column",gap:4},p.style||{})}>{p.label&&<label style={{fontSize:11,fontWeight:600,color:C.mut,textTransform:"uppercase",letterSpacing:".04em"}}>{p.label}</label>}<select value={p.value} onChange={function(e){p.onChange(e.target.value);}} style={{padding:"8px 12px",background:C.inp,border:"1px solid "+C.brd,borderRadius:8,color:C.txt,fontSize:13,fontFamily:"inherit",outline:"none"}}>{p.options.map(function(o){return <option key={o.v} value={o.v}>{o.l}</option>;})}</select></div>;}
function SC(p){var color=p.color||C.acc;return <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:"20px 22px",flex:1,minWidth:170,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-20,right:-20,width:100,height:100,background:"radial-gradient(circle,"+color+"15,transparent 70%)"}}></div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><div style={{width:34,height:34,borderRadius:9,background:color+"14",display:"flex",alignItems:"center",justifyContent:"center"}}><Ic d={p.icon} s={16} c={color}/></div><span style={{fontSize:11,color:C.mut,fontWeight:600,textTransform:"uppercase"}}>{p.label}</span></div><div style={{fontSize:24,fontWeight:700,color:C.txt,fontFeatureSettings:"'tnum'"}}>{p.value}</div>{p.sub&&<div style={{fontSize:11,color:C.mut,marginTop:3}}>{p.sub}</div>}</div>;}
function PBar(p){var h=p.h||8;return <div style={{width:"100%",background:C.hov,borderRadius:h,height:h,overflow:"hidden"}}><div style={{width:Math.min(p.value/p.max*100,100)+"%",height:"100%",background:p.color||C.g,borderRadius:h,transition:"width .5s"}}></div></div>;}
function Tbl(p){return <div style={{overflowX:"auto",borderRadius:12,border:"1px solid "+C.brd}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13}}><thead><tr style={{background:C.hov}}>{p.cols.map(function(c,i){return <th key={i} style={{padding:"11px 14px",textAlign:"left",color:C.mut,fontWeight:600,fontSize:10,textTransform:"uppercase",borderBottom:"1px solid "+C.brd,whiteSpace:"nowrap"}}>{c.label}</th>;})}</tr></thead><tbody>{p.data.length===0&&<tr><td colSpan={p.cols.length} style={{padding:40,textAlign:"center",color:C.dim}}>No data</td></tr>}{p.data.map(function(row,ri){return <tr key={ri} onClick={function(){if(p.onRow)p.onRow(row);}} style={{borderBottom:"1px solid "+C.brd,cursor:p.onRow?"pointer":"default"}} onMouseEnter={function(e){e.currentTarget.style.background=C.hov;}} onMouseLeave={function(e){e.currentTarget.style.background="transparent";}}>{p.cols.map(function(c,ci){return <td key={ci} style={{padding:"10px 14px",color:C.txt,whiteSpace:"nowrap"}}>{c.render?c.render(row):row[c.key]}</td>;})}</tr>;})}</tbody></table></div>;}
function Modal(p){if(!p.open)return null;return <div onClick={p.onClose} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.65)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(4px)"}}><div onClick={function(e){e.stopPropagation();}} style={{background:C.card,border:"1px solid "+C.brd,borderRadius:16,padding:28,width:p.wide?700:480,maxWidth:"92vw",maxHeight:"85vh",overflowY:"auto",boxShadow:"0 25px 60px rgba(0,0,0,.5)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h3 style={{fontSize:17,fontWeight:700,color:C.txt,margin:0}}>{p.title}</h3><button type="button" onClick={p.onClose} style={{background:"none",border:"none",cursor:"pointer",color:C.mut,padding:4}}><Ic d={icons.x} s={18}/></button></div>{p.children}</div></div>;}

/* ── Export Modal: Download file + Copy to Clipboard ── */
function ExportModal(p){
  var [copied,setCopied]=useState(false);
  var [dlOk,setDlOk]=useState(false);
  var mime=p.type==="json"?"application/json":"text/csv";

  function doCopy(){
    try{
      navigator.clipboard.writeText(p.content).then(function(){setCopied(true);setTimeout(function(){setCopied(false);},2000);});
    }catch(e){
      var ta=document.createElement("textarea");ta.value=p.content;ta.style.cssText="position:fixed;left:-9999px;top:-9999px";document.body.appendChild(ta);ta.focus();ta.select();
      try{document.execCommand("copy");setCopied(true);setTimeout(function(){setCopied(false);},2000);}catch(ex){}
      document.body.removeChild(ta);
    }
  }

  function doDownload(){
    var ok=triggerDownload(p.filename,p.content,mime);
    setDlOk(true);setTimeout(function(){setDlOk(false);},2000);
  }

  if(!p.open)return null;
  var dataHref="data:"+mime+";charset=utf-8,"+encodeURIComponent(p.content);

  return <div onClick={p.onClose} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.7)",zIndex:1100,display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(4px)"}}>
    <div onClick={function(e){e.stopPropagation();}} style={{background:C.card,border:"1px solid "+C.brd,borderRadius:16,padding:28,width:640,maxWidth:"92vw",maxHeight:"85vh",display:"flex",flexDirection:"column",boxShadow:"0 25px 60px rgba(0,0,0,.5)"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
        <div>
          <h3 style={{fontSize:17,fontWeight:700,color:C.txt,margin:0}}>{p.filename}</h3>
          <span style={{fontSize:11,color:C.mut}}>{p.type==="csv"?"CSV Spreadsheet":"JSON Data"}</span>
        </div>
        <button type="button" onClick={p.onClose} style={{background:"none",border:"none",cursor:"pointer",color:C.mut,padding:4}}><Ic d={icons.x} s={18}/></button>
      </div>
      <div style={{flex:1,overflow:"auto",marginBottom:16}}>
        <pre style={{background:C.bg,border:"1px solid "+C.brd,borderRadius:10,padding:16,fontSize:11,color:C.txt,lineHeight:1.5,margin:0,whiteSpace:"pre-wrap",wordBreak:"break-all",maxHeight:300,overflow:"auto",fontFamily:"'SF Mono','Fira Code',monospace"}}>{p.content}</pre>
      </div>
      <div style={{display:"flex",gap:8,justifyContent:"flex-end",flexWrap:"wrap"}}>
        <Btn v="ghost" onClick={p.onClose}>Close</Btn>
        <Btn v={copied?"success":"secondary"} onClick={doCopy}>
          <Ic d={copied?icons.check:icons.clip} s={14} c={copied?"#fff":C.txt}/>
          {copied?"Copied!":"Copy to Clipboard"}
        </Btn>
        <a href={dataHref} download={p.filename} style={{textDecoration:"none"}}>
          <Btn v={dlOk?"success":"primary"} onClick={function(){setDlOk(true);setTimeout(function(){setDlOk(false);},2000);}}>
            <Ic d={dlOk?icons.check:icons.dl} s={14} c="#fff"/>
            {dlOk?"Downloaded!":"Download "+p.filename}
          </Btn>
        </a>
      </div>
    </div>
  </div>;
}

var L={en:{dashboard:"Dashboard",revenue:"Revenue",vatDue:"VAT Due",employees:"Employees",omani:"Omani",expat:"Expat",total:"Total",spfMonth:"Monthly SPF",payroll:"Payroll",invoices:"Invoices",pending:"Pending",overdue:"Overdue",paid:"Paid",cancelled:"Cancelled",invNo:"Invoice #",client:"Client",date:"Date",subtotal:"Subtotal",vat:"VAT",status:"Status",recentInv:"Recent Invoices",omanOv:"Omanization",newInv:"New Invoice",clientAr:"Client (AR)",clientEn:"Client (EN)",currency:"Currency",items:"Items",descAr:"Desc (AR)",descEn:"Desc (EN)",qty:"Qty",price:"Price",addItem:"+ Add Item",create:"Create",back:"← Back",notes:"Notes",addEmp:"Add Employee",editEmp:"Edit Employee",nameAr:"Name (AR)",nameEn:"Name (EN)",nationality:"Nationality",department:"Department",salary:"Salary",role:"Role",joinDate:"Joined",save:"Save",name:"Name",vatComp:"VAT Compliance",outputVAT:"Output VAT",inputVAT:"Input VAT",netVAT:"Net VAT",vatReturn:"VAT Return",download:"Download",submit:"Submit",checklist:"Checklist",taxReg:"Tax Registered",invOk:"Invoices OK",retFiled:"Return Filed",payDone:"Payment Done",recsKept:"Records Kept 5yr",spf:"Social Protection",erContrib:"Employer",eeContrib:"Employee",gvContrib:"Government",monthlyTotal:"Monthly Total",eligible:"eligible",breakdown:"Breakdown",employer:"Employer",employee:"Employee",govt:"Govt",spfNo:"SPF #",basicSal:"Basic Salary",erShare:"ER Share",eeShare:"EE Share",totalCont:"Total",dlSPF:"Export SPF",submitSPF:"Submit SPF",oman:"Omanization",overallRate:"Overall",compliant:"Compliant",nonComp:"Non-Compliant",actionNeeded:"Action Needed",current:"Current",target:"Target",needHire:"Need to hire",moreOmanis:"more Omanis",payrollMod:"Payroll",basic:"Basic",allowances:"Allowances",netPay:"Net Pay",spfDed:"SPF Ded.",runPayroll:"Run Payroll",payslip:"Pay Slip",expenses:"Expenses",addExp:"Add Expense",category:"Category",vendor:"Vendor",amount:"Amount",vatInc:"VAT Incl.",rent:"Rent",utilities:"Utilities",supplies:"Supplies",insurance:"Insurance",otherExp:"Other",reports:"Reports",incomeStatement:"Income Statement",totalIncome:"Income",totalExp:"Expenses",netProfit:"Net Profit",grossMargin:"Margin",settings:"Settings",compName:"Company (AR)",compNameEn:"Company (EN)",crNo:"CR No.",taxId:"Tax ID",address:"Address",email:"Email",language:"Language",saveSettings:"Save Settings",appTitle:"Oman SME ERP",appSub:"Enterprise Solutions",markPaid:"Mark Paid",cancelInv:"Cancel",duplicate:"Duplicate",confirmDel:"Confirm delete?",confirm:"Confirm",cancel:"Cancel",search:"Search...",notifications:"Notifications",noNotif:"No notifications",clearAll:"Clear All",emailInv:"Email",printInv:"Print",payslipTitle:"Monthly Pay Slip",export:"Export",omanReport:"Oman Report",taxableSales:"Taxable Sales",deductible:"Deductible Input",netPayable:"Net Payable",ok:"Success",created:"Created",updated:"Updated",deleted:"Deleted",sent:"Email Sent",payrollDone:"Payroll Complete",submitted:"Submitted"},
ar:{dashboard:"لوحة المعلومات",revenue:"الإيرادات",vatDue:"ضريبة مستحقة",employees:"الموظفون",omani:"عُماني",expat:"وافد",total:"الإجمالي",spfMonth:"اشتراكات الحماية",payroll:"الرواتب",invoices:"الفواتير",pending:"معلقة",overdue:"متأخرة",paid:"مدفوعة",cancelled:"ملغاة",invNo:"رقم الفاتورة",client:"العميل",date:"التاريخ",subtotal:"الفرعي",vat:"ض.ق.م",status:"الحالة",recentInv:"أحدث الفواتير",omanOv:"التعمين",newInv:"فاتورة جديدة",clientAr:"العميل (ع)",clientEn:"العميل (EN)",currency:"العملة",items:"البنود",descAr:"الوصف (ع)",descEn:"الوصف (EN)",qty:"الكمية",price:"السعر",addItem:"+ إضافة",create:"إنشاء",back:"→ رجوع",notes:"ملاحظات",addEmp:"إضافة موظف",editEmp:"تعديل",nameAr:"الاسم (ع)",nameEn:"الاسم (EN)",nationality:"الجنسية",department:"القسم",salary:"الراتب",role:"الوظيفة",joinDate:"الالتحاق",save:"حفظ",name:"الاسم",vatComp:"الامتثال الضريبي",outputVAT:"ضريبة المخرجات",inputVAT:"ضريبة المدخلات",netVAT:"صافي الضريبة",vatReturn:"الإقرار الضريبي",download:"تحميل",submit:"تقديم",checklist:"قائمة الامتثال",taxReg:"مسجل ضريبياً",invOk:"فواتير متوافقة",retFiled:"تم تقديم الإقرار",payDone:"تم السداد",recsKept:"سجلات محفوظة",spf:"صندوق الحماية",erContrib:"حصة المنشأة",eeContrib:"حصة الموظف",gvContrib:"حصة الحكومة",monthlyTotal:"إجمالي شهري",eligible:"مؤهل",breakdown:"تفصيل",employer:"صاحب العمل",employee:"الموظف",govt:"الحكومة",spfNo:"رقم الحماية",basicSal:"الأساسي",erShare:"حصة المنشأة",eeShare:"حصة الموظف",totalCont:"الإجمالي",dlSPF:"تصدير",submitSPF:"تقديم",oman:"التعمين",overallRate:"النسبة",compliant:"ملتزم",nonComp:"غير ملتزم",actionNeeded:"يتطلب إجراء",current:"الحالي",target:"المستهدف",needHire:"يجب توظيف",moreOmanis:"عُمانيين",payrollMod:"كشف الرواتب",basic:"أساسي",allowances:"بدلات",netPay:"صافي الراتب",spfDed:"خصم الحماية",runPayroll:"تشغيل",payslip:"قسيمة",expenses:"المصروفات",addExp:"إضافة",category:"الفئة",vendor:"المورد",amount:"المبلغ",vatInc:"شامل الضريبة",rent:"إيجار",utilities:"مرافق",supplies:"لوازم",insurance:"تأمين",otherExp:"أخرى",reports:"التقارير",incomeStatement:"قائمة الدخل",totalIncome:"الدخل",totalExp:"المصروفات",netProfit:"صافي الربح",grossMargin:"هامش الربح",settings:"الإعدادات",compName:"الشركة (ع)",compNameEn:"الشركة (EN)",crNo:"السجل التجاري",taxId:"الرقم الضريبي",address:"العنوان",email:"البريد",language:"اللغة",saveSettings:"حفظ",appTitle:"نظام إدارة المنشآت",appSub:"حلول عُمانية",markPaid:"تحديد كمدفوعة",cancelInv:"إلغاء",duplicate:"نسخ",confirmDel:"تأكيد الحذف؟",confirm:"تأكيد",cancel:"إلغاء",search:"بحث...",notifications:"الإشعارات",noNotif:"لا إشعارات",clearAll:"مسح",emailInv:"إرسال",printInv:"طباعة",payslipTitle:"قسيمة الراتب",export:"تصدير",omanReport:"تقرير التعمين",taxableSales:"مبيعات خاضعة",deductible:"مدخلات قابلة للخصم",netPayable:"صافي مستحق",ok:"تم بنجاح",created:"تم الإنشاء",updated:"تم التحديث",deleted:"تم الحذف",sent:"تم الإرسال",payrollDone:"تم التشغيل",submitted:"تم التقديم"}};

export default function App(){
  var [lang,setLang]=useState("en"),[page,setPage]=useState("dashboard"),[emps,setEmps]=useState(initEmp),[invs,setInvs]=useState(initInv),[exps,setExps]=useState(initExp);
  var [col,setCol]=useState(false),[toasts,setToasts]=useState([]),[notifOpen,setNotifOpen]=useState(false);
  var [searchQ,setSearchQ]=useState(""),[searchOpen,setSearchOpen]=useState(false);
  var [notifs,setNotifs]=useState([{id:1,msg:"INV-003 overdue",type:"w",read:false},{id:2,msg:"SPF due 5 days",type:"i",read:false},{id:3,msg:"Omanization gap",type:"e",read:false}]);
  var [co,setCo]=useState({nameAr:"شركة المستقبل للتقنية",nameEn:"Future Tech LLC",cr:"1234567",taxId:"OM1234567890",address:"بوشر، مسقط",email:"info@futuretech.om"});

  /* ── EXPORT MODAL STATE (global) ── */
  var [expModal,setExpModal]=useState({open:false,filename:"",content:"",type:"csv"});
  function showExport(filename,content,type){setExpModal({open:true,filename:filename,content:content,type:type||"csv"});}

  function t(k){return(L[lang]&&L[lang][k])||k;}
  function toast(msg,tp){var id=uid();setToasts(function(p){return p.concat([{id:id,msg:msg,type:tp||"s"}]);});setTimeout(function(){setToasts(function(p){return p.filter(function(x){return x.id!==id;});});},3000);}

  var navItems=[{k:"dashboard",i:icons.home},{k:"invoices",i:icons.file},{k:"employees",i:icons.users},{k:"payroll",i:icons.card},{k:"expenses",i:icons.wallet},{k:"vat",i:icons.dollar},{k:"spf",i:icons.shield},{k:"omanization",i:icons.flag},{k:"reports",i:icons.chart},{k:"settings",i:icons.gear}];
  var navLabels={dashboard:t("dashboard"),invoices:t("invoices"),employees:t("employees"),payroll:t("payrollMod"),expenses:t("expenses"),vat:t("vatComp"),spf:t("spf"),omanization:t("oman"),reports:t("reports"),settings:t("settings")};
  var sr=useMemo(function(){if(!searchQ.trim())return[];var q=searchQ.toLowerCase(),r=[];emps.forEach(function(e){if(e.nameEn.toLowerCase().indexOf(q)>=0)r.push({l:e.nameEn,s:e.roleEn,p:"employees"});});invs.forEach(function(inv){if(inv.id.toLowerCase().indexOf(q)>=0||inv.clientEn.toLowerCase().indexOf(q)>=0)r.push({l:inv.id,s:inv.clientEn,p:"invoices"});});return r.slice(0,5);},[searchQ,emps,invs]);

  function renderPage(){
    if(page==="dashboard"){
      var rev=invs.filter(function(i){return i.status==="paid";}).reduce(function(s,i){return s+iTotal(i);},0);var om=emps.filter(function(e){return e.nat==="Omani";}).length;var tp=emps.reduce(function(s,e){return s+e.salary+e.allow;},0);var spfT=emps.filter(function(e){return e.nat==="Omani";}).reduce(function(s,e){return s+e.salary*(SPF_ER+SPF_EE);},0);var exT=exps.reduce(function(s,e){return s+e.amount;},0);
      return <div><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:"0 0 24px"}}>{t("dashboard")}</h2>
        <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.dollar} label={t("revenue")} value={fmt(rev)} sub={t("vatDue")+": "+fmt(invs.reduce(function(s,i){return s+iVat(i);},0))} color={C.g}/><SC icon={icons.users} label={t("employees")} value={emps.length} sub={om+" "+t("omani")} color={C.b}/><SC icon={icons.shield} label={t("spfMonth")} value={fmt(spfT)} color={C.gld}/><SC icon={icons.wallet} label={t("expenses")} value={fmt(exT)} color={C.acc}/></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:14,fontWeight:700,color:C.txt,marginBottom:16}}>{t("omanOv")}</h3>{Object.entries(emps.reduce(function(a,e){if(!a[e.dept])a[e.dept]={t:0,o:0};a[e.dept].t++;if(e.nat==="Omani")a[e.dept].o++;return a;},{})).map(function(en){var dept=en[0],d=en[1],pct=Math.round(d.o/d.t*100),tg=TARGETS[dept]||20;return <div key={dept} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,marginBottom:4}}><span style={{color:C.txt}}>{dept}</span><span style={{color:pct>=tg?C.g:C.y}}>{pct}%/{tg}%</span></div><PBar value={pct} max={tg} color={pct>=tg?C.g:C.y}/></div>;})}</div>
          <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:14,fontWeight:700,color:C.txt,marginBottom:16}}>{t("recentInv")}</h3>{invs.slice(0,4).map(function(inv){return <div key={inv.id} onClick={function(){setPage("invoices");}} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:"1px solid "+C.brd,cursor:"pointer"}}><div><div style={{fontSize:13,fontWeight:600,color:C.txt}}>{inv.id}</div><div style={{fontSize:11,color:C.mut}}>{inv.clientEn}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:13,fontWeight:600,color:C.txt}}>{fmt(iGrand(inv))}</div><Badge color={inv.status==="paid"?"g":inv.status==="pending"?"y":"r"}>{t(inv.status)}</Badge></div></div>;})}</div>
        </div></div>;
    }
    if(page==="invoices") return <InvPage invs={invs} setInvs={setInvs} t={t} toast={toast} co={co} showExport={showExport}/>;
    if(page==="employees") return <EmpPage emps={emps} setEmps={setEmps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="payroll") return <PayPage emps={emps} t={t} toast={toast} co={co} showExport={showExport}/>;
    if(page==="expenses") return <ExpPage exps={exps} setExps={setExps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="vat") return <VATPage invs={invs} exps={exps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="spf") return <SPFPage emps={emps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="omanization") return <OmanPage emps={emps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="reports") return <RepPage invs={invs} emps={emps} exps={exps} t={t} toast={toast} showExport={showExport}/>;
    if(page==="settings") return <SetPage co={co} setCo={setCo} lang={lang} setLang={setLang} t={t} toast={toast} emps={emps} invs={invs} exps={exps} showExport={showExport}/>;
    return null;
  }

  return <div dir={lang==="ar"?"rtl":"ltr"} style={{display:"flex",minHeight:"100vh",background:C.bg,fontFamily:"'DM Sans','Segoe UI',sans-serif",color:C.txt}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
    <style>{`@keyframes sIn{from{transform:translateY(10px);opacity:0}to{transform:translateY(0);opacity:1}}*{box-sizing:border-box}select option{background:${C.card};color:${C.txt}}input[type=checkbox]{accent-color:${C.acc}}`}</style>

    {/* Export Modal */}
    <ExportModal open={expModal.open} filename={expModal.filename} content={expModal.content} type={expModal.type} onClose={function(){setExpModal({open:false,filename:"",content:"",type:"csv"});}}/>

    {/* Toasts */}
    <div style={{position:"fixed",bottom:24,right:24,zIndex:2000,display:"flex",flexDirection:"column",gap:8}}>{toasts.map(function(tt){return <div key={tt.id} style={{padding:"12px 20px",borderRadius:10,background:tt.type==="e"?C.r:C.g,color:"#fff",fontSize:13,fontWeight:600,boxShadow:"0 8px 24px rgba(0,0,0,.3)",animation:"sIn .3s ease",minWidth:240}}>{tt.msg}</div>;})}</div>

    {/* Sidebar */}
    <div style={{width:col?62:220,background:C.bg2,borderRight:"1px solid "+C.brd,display:"flex",flexDirection:"column",transition:"width .2s",flexShrink:0}}>
      <div style={{padding:col?"16px 10px":"16px 18px",borderBottom:"1px solid "+C.brd}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,"+C.acc+","+C.accL+")",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{fontSize:17,fontWeight:800,color:"#fff"}}>ع</span></div>{!col&&<div><div style={{fontSize:14,fontWeight:800,color:C.txt}}>{t("appTitle")}</div><div style={{fontSize:9,color:C.mut}}>{t("appSub")}</div></div>}</div></div>
      <div style={{padding:"10px 6px",flex:1,overflowY:"auto"}}>{navItems.map(function(ni){var active=page===ni.k;return <button key={ni.k} type="button" onClick={function(){setPage(ni.k);}} style={{width:"100%",display:"flex",alignItems:"center",gap:9,padding:col?"9px 0":"9px 12px",marginBottom:1,borderRadius:8,border:"none",cursor:"pointer",background:active?C.accG:"transparent",color:active?C.acc:C.mut,fontSize:13,fontWeight:active?600:500,fontFamily:"inherit",justifyContent:col?"center":"flex-start"}}><Ic d={ni.i} s={17} c={active?C.acc:C.dim}/>{!col&&(navLabels[ni.k]||ni.k)}</button>;})}</div>
      <div style={{padding:10,borderTop:"1px solid "+C.brd}}><button type="button" onClick={function(){setLang(lang==="ar"?"en":"ar");}} style={{width:"100%",display:"flex",alignItems:"center",justifyContent:col?"center":"flex-start",gap:8,padding:"8px 12px",borderRadius:8,border:"1px solid "+C.brd,background:C.hov,color:C.mut,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}><Ic d={icons.globe} s={15}/>{!col&&(lang==="ar"?"English":"العربية")}</button></div>
    </div>

    {/* Main */}
    <div style={{flex:1,overflow:"auto",display:"flex",flexDirection:"column"}}>
      <div style={{padding:"10px 24px",borderBottom:"1px solid "+C.brd,display:"flex",alignItems:"center",justifyContent:"space-between",background:C.bg2,flexShrink:0}}>
        <div style={{display:"flex",alignItems:"center",gap:12}}>
          <button type="button" onClick={function(){setCol(!col);}} style={{background:"none",border:"none",cursor:"pointer",padding:4,color:C.mut}}><Ic d={icons.menu} s={18}/></button>
          <div style={{position:"relative"}}><div style={{display:"flex",alignItems:"center",gap:6,padding:"6px 12px",background:C.inp,borderRadius:8,border:"1px solid "+(searchOpen?C.acc:C.brd),width:260}}><Ic d={icons.search} s={14} c={C.dim}/><input value={searchQ} onChange={function(e){setSearchQ(e.target.value);setSearchOpen(true);}} onFocus={function(){setSearchOpen(true);}} onBlur={function(){setTimeout(function(){setSearchOpen(false);},200);}} placeholder={t("search")} style={{background:"none",border:"none",color:C.txt,fontSize:13,fontFamily:"inherit",outline:"none",width:"100%"}}/>{searchQ&&<button type="button" onClick={function(){setSearchQ("");}} style={{background:"none",border:"none",cursor:"pointer",color:C.mut,padding:0}}><Ic d={icons.x} s={14}/></button>}</div>
            {searchOpen&&sr.length>0&&<div style={{position:"absolute",top:"100%",left:0,right:0,marginTop:4,background:C.card,border:"1px solid "+C.brd,borderRadius:10,boxShadow:"0 12px 32px rgba(0,0,0,.4)",zIndex:100}}>{sr.map(function(r,i){return <button key={i} type="button" onMouseDown={function(){setPage(r.p);setSearchQ("");setSearchOpen(false);}} style={{width:"100%",display:"flex",alignItems:"center",gap:10,padding:"10px 14px",background:"transparent",border:"none",borderBottom:"1px solid "+C.brd,color:C.txt,fontSize:13,cursor:"pointer",fontFamily:"inherit",textAlign:"left"}}><div><div style={{fontWeight:600}}>{r.l}</div><div style={{fontSize:11,color:C.mut}}>{r.s}</div></div></button>;})}</div>}
          </div>
        </div>
        <div style={{display:"flex",alignItems:"center",gap:10}}>
          <div style={{display:"flex",alignItems:"center",gap:5,padding:"4px 10px",background:C.gB,borderRadius:20,border:"1px solid "+C.gD}}><div style={{width:5,height:5,borderRadius:"50%",background:C.g}}/><span style={{fontSize:10,fontWeight:600,color:C.g}}>Tax Auth</span></div>
          <div style={{position:"relative"}}><button type="button" onClick={function(){setNotifOpen(!notifOpen);}} style={{background:"none",border:"none",cursor:"pointer",position:"relative",padding:4,color:C.mut}}><Ic d={icons.bell} s={18}/>{notifs.filter(function(n){return!n.read;}).length>0&&<div style={{position:"absolute",top:0,right:0,width:14,height:14,borderRadius:"50%",background:C.r,color:"#fff",fontSize:8,fontWeight:800,display:"flex",alignItems:"center",justifyContent:"center"}}>{notifs.filter(function(n){return!n.read;}).length}</div>}</button>
            {notifOpen&&<div style={{position:"absolute",top:"100%",right:0,marginTop:8,width:300,background:C.card,border:"1px solid "+C.brd,borderRadius:12,boxShadow:"0 12px 32px rgba(0,0,0,.4)",zIndex:100}}><div style={{padding:"12px 16px",borderBottom:"1px solid "+C.brd,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:14,fontWeight:700,color:C.txt}}>{t("notifications")}</span><Btn v="ghost" s="sm" onClick={function(){setNotifs([]);setNotifOpen(false);toast(t("clearAll"));}}>{t("clearAll")}</Btn></div>{notifs.length===0&&<div style={{padding:24,textAlign:"center",color:C.dim}}>{t("noNotif")}</div>}{notifs.map(function(n){return <div key={n.id} onClick={function(){setNotifs(function(p){return p.map(function(x){return x.id===n.id?Object.assign({},x,{read:true}):x;});});}} style={{padding:"12px 16px",borderBottom:"1px solid "+C.brd,cursor:"pointer",background:n.read?"transparent":C.hov}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:6,height:6,borderRadius:"50%",background:n.read?"transparent":n.type==="e"?C.r:C.y}}/><span style={{fontSize:12,color:C.txt}}>{n.msg}</span></div></div>;})}</div>}
          </div>
          <div onClick={function(){setPage("settings");}} style={{width:32,height:32,borderRadius:"50%",background:"linear-gradient(135deg,"+C.acc+","+C.accL+")",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,color:"#fff",cursor:"pointer"}}>م</div>
        </div>
      </div>
      <div style={{padding:24,flex:1}}>{renderPage()}</div>
    </div>
  </div>;
}

/* ══════════════════════ PAGES ══════════════════════ */
function InvPage(p){var t=p.t,invs=p.invs,setInvs=p.setInvs,toast=p.toast,co=p.co,showExport=p.showExport;
  var [showC,setShowC]=useState(false),[viewI,setViewI]=useState(null),[fil,setFil]=useState("all");
  var [nI,setNI]=useState({client:"",clientEn:"",cur:"OMR",items:[{desc:"",descEn:"",qty:1,price:0}],notes:""});
  function doCreate(){if(!nI.clientEn&&!nI.client){toast("Client required","e");return;}var id="INV-"+String(invs.length+1).padStart(3,"0");setInvs(invs.concat([Object.assign({},nI,{id:id,date:today(),due:new Date(Date.now()+30*864e5).toISOString().slice(0,10),status:"pending"})]));setShowC(false);setNI({client:"",clientEn:"",cur:"OMR",items:[{desc:"",descEn:"",qty:1,price:0}],notes:""});toast(t("created"));}
  function doStatus(inv,st){setInvs(invs.map(function(i){return i.id===inv.id?Object.assign({},i,{status:st}):i;}));toast(t("updated"));}
  function doDup(inv){var id="INV-"+String(invs.length+1).padStart(3,"0");setInvs(invs.concat([Object.assign({},inv,{id:id,date:today(),status:"pending"})]));toast(t("created"));}
  function doDel(inv){setInvs(invs.filter(function(i){return i.id!==inv.id;}));setViewI(null);toast(t("deleted"));}
  function doExport(){showExport("invoices.csv",buildCSV(["#","Client","Date","Total","Status"],invs.map(function(i){return[i.id,i.clientEn,i.date,iGrand(i).toFixed(3),i.status];})),"csv");}
  var fd=fil==="all"?invs:invs.filter(function(i){return i.status===fil;});
  if(viewI){var inv=viewI,sub=iTotal(inv),vat=iVat(inv),grand=iGrand(inv);
    return <div><div style={{display:"flex",gap:8,marginBottom:20,flexWrap:"wrap"}}><Btn v="ghost" s="sm" onClick={function(){setViewI(null);}}>{t("back")}</Btn><Btn v="secondary" s="sm" onClick={function(){window.print();}}><Ic d={icons.print} s={14}/> {t("printInv")}</Btn><Btn v="secondary" s="sm" onClick={function(){toast(t("sent"));}}><Ic d={icons.send} s={14}/> {t("emailInv")}</Btn>{inv.status==="pending"&&<Btn v="success" s="sm" onClick={function(){doStatus(inv,"paid");setViewI(Object.assign({},inv,{status:"paid"}));}}><Ic d={icons.check} s={14}/> {t("markPaid")}</Btn>}{inv.status!=="cancelled"&&<Btn v="danger" s="sm" onClick={function(){doStatus(inv,"cancelled");setViewI(Object.assign({},inv,{status:"cancelled"}));}}>{t("cancelInv")}</Btn>}<Btn v="secondary" s="sm" onClick={function(){doDup(inv);}}><Ic d={icons.copy} s={14}/> {t("duplicate")}</Btn><Btn v="ghost" s="sm" onClick={function(){doDel(inv);}} style={{color:C.r}}><Ic d={icons.trash} s={14} c={C.r}/></Btn></div>
      <div style={{background:"#fff",color:"#111",borderRadius:14,padding:40,maxWidth:800,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",borderBottom:"3px solid #c44530",paddingBottom:20,marginBottom:24}}><div><div style={{fontSize:24,fontWeight:800,color:"#c44530"}}>{co.nameAr}</div><div style={{fontSize:13,color:"#666"}}>{co.nameEn}</div><div style={{fontSize:11,color:"#888",marginTop:8}}>{co.address} | CR: {co.cr} | Tax: {co.taxId}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:20,fontWeight:700}}>فاتورة ضريبية</div><div style={{fontSize:12,color:"#666"}}>Tax Invoice</div><div style={{marginTop:12,fontSize:12,color:"#555",lineHeight:1.8}}><div>{inv.id}</div><div>{fD(inv.date)}</div><div>{t(inv.status)}</div></div></div></div>
        <div style={{marginBottom:24,padding:14,background:"#f8f8f8",borderRadius:8}}><div style={{fontSize:15,fontWeight:600}}>{inv.client}</div><div style={{fontSize:12,color:"#666"}}>{inv.clientEn}</div></div>
        <table style={{width:"100%",borderCollapse:"collapse",marginBottom:24,fontSize:13}}><thead><tr style={{background:"#f0f0f0"}}><th style={{padding:10,textAlign:"left"}}>Description</th><th style={{padding:10,width:60}}>Qty</th><th style={{padding:10,textAlign:"right",width:100}}>Price</th><th style={{padding:10,textAlign:"right",width:100}}>Total</th></tr></thead><tbody>{inv.items.map(function(item,i){return <tr key={i} style={{borderBottom:"1px solid #eee"}}><td style={{padding:10}}><div>{item.desc}</div><div style={{fontSize:11,color:"#888"}}>{item.descEn}</div></td><td style={{padding:10,textAlign:"center"}}>{item.qty}</td><td style={{padding:10,textAlign:"right"}}>{fmt(item.price,inv.cur)}</td><td style={{padding:10,textAlign:"right",fontWeight:600}}>{fmt(item.qty*item.price,inv.cur)}</td></tr>;})}</tbody></table>
        <div style={{display:"flex",justifyContent:"flex-end"}}><div style={{width:260}}><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:13}}><span>{t("subtotal")}</span><span>{fmt(sub,inv.cur)}</span></div><div style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:13}}><span>{t("vat")} 5%</span><span>{fmt(vat,inv.cur)}</span></div><div style={{display:"flex",justifyContent:"space-between",padding:"10px 0",fontSize:16,fontWeight:700,borderTop:"2px solid #c44530",marginTop:8}}><span>{t("total")}</span><span>{fmt(grand,inv.cur)}</span></div></div></div></div></div>;}
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("invoices")}</h2><div style={{display:"flex",gap:8}}><Btn v="secondary" s="sm" onClick={doExport}><Ic d={icons.dl} s={14}/> {t("export")}</Btn><Btn onClick={function(){setShowC(true);}}><Ic d={icons.plus} s={14} c="#fff"/> {t("newInv")}</Btn></div></div>
    <div style={{display:"flex",gap:6,marginBottom:16}}>{["all","pending","paid","overdue","cancelled"].map(function(s){return <button key={s} type="button" onClick={function(){setFil(s);}} style={{padding:"6px 14px",borderRadius:20,border:"1px solid "+(fil===s?C.acc:C.brd),background:fil===s?C.accG:"transparent",color:fil===s?C.acc:C.mut,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>{s==="all"?t("total"):t(s)}</button>;})}</div>
    <Modal open={showC} onClose={function(){setShowC(false);}} title={t("newInv")} wide>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}><Inp label={t("clientAr")} value={nI.client} onChange={function(v){setNI(Object.assign({},nI,{client:v}));}}/><Inp label={t("clientEn")} value={nI.clientEn} onChange={function(v){setNI(Object.assign({},nI,{clientEn:v}));}}/></div>
      {nI.items.map(function(item,idx){return <div key={idx} style={{display:"grid",gridTemplateColumns:"2fr 2fr 70px 100px",gap:8,marginBottom:6}}><Inp label={idx===0?t("descAr"):""} value={item.desc} onChange={function(v){var items=nI.items.slice();items[idx]=Object.assign({},items[idx],{desc:v});setNI(Object.assign({},nI,{items:items}));}}/><Inp label={idx===0?t("descEn"):""} value={item.descEn} onChange={function(v){var items=nI.items.slice();items[idx]=Object.assign({},items[idx],{descEn:v});setNI(Object.assign({},nI,{items:items}));}}/><Inp label={idx===0?t("qty"):""} type="number" value={item.qty} onChange={function(v){var items=nI.items.slice();items[idx]=Object.assign({},items[idx],{qty:Number(v)});setNI(Object.assign({},nI,{items:items}));}}/><Inp label={idx===0?t("price"):""} type="number" value={item.price} onChange={function(v){var items=nI.items.slice();items[idx]=Object.assign({},items[idx],{price:Number(v)});setNI(Object.assign({},nI,{items:items}));}}/></div>;})}
      <div style={{display:"flex",gap:8,marginTop:14}}><Btn v="secondary" s="sm" onClick={function(){setNI(Object.assign({},nI,{items:nI.items.concat([{desc:"",descEn:"",qty:1,price:0}])}));}}>{t("addItem")}</Btn><div style={{flex:1}}/><Btn v="ghost" onClick={function(){setShowC(false);}}>{t("cancel")}</Btn><Btn onClick={doCreate}>{t("create")}</Btn></div>
    </Modal>
    <Tbl cols={[{key:"id",label:t("invNo"),render:function(r){return <span style={{fontWeight:600,color:C.acc}}>{r.id}</span>;}},{key:"client",label:t("client"),render:function(r){return r.clientEn;}},{key:"date",label:t("date"),render:function(r){return fD(r.date);}},{key:"total",label:t("total"),render:function(r){return <strong>{fmt(iGrand(r),r.cur)}</strong>;}},{key:"status",label:t("status"),render:function(r){return <Badge color={r.status==="paid"?"g":r.status==="pending"?"y":r.status==="overdue"?"r":"b"}>{t(r.status)}</Badge>;}},{key:"act",label:"",render:function(r){return <div style={{display:"flex",gap:4}}><Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();setViewI(r);}}><Ic d={icons.eye} s={14}/></Btn>{r.status==="pending"&&<Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();doStatus(r,"paid");}}><Ic d={icons.check} s={14} c={C.g}/></Btn>}<Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();doDup(r);}}><Ic d={icons.copy} s={14}/></Btn><Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();doDel(r);}}><Ic d={icons.trash} s={14} c={C.r}/></Btn></div>;}}]} data={fd} onRow={function(r){setViewI(r);}}/></div>;}

function EmpPage(p){var t=p.t,emps=p.emps,setEmps=p.setEmps,toast=p.toast,showExport=p.showExport;
  var [showF,setShowF]=useState(false),[editE,setEditE]=useState(null),[delE,setDelE]=useState(null);
  var empty={name:"",nameEn:"",nat:"Omani",dept:"IT & Telecom",salary:0,allow:0,roleEn:"",email:"",bank:"Bank Muscat"};var [form,setForm]=useState(empty);
  function doSave(){if(!form.nameEn){toast("Name required","e");return;}if(editE){setEmps(emps.map(function(e){return e.id===editE.id?Object.assign({},e,form):e;}));toast(t("updated"));}else{var id=maxId(emps)+1;setEmps(emps.concat([Object.assign({},form,{id:id,join:today(),spf:form.nat==="Omani"?"SPF-"+String(id).padStart(3,"0"):"—"})]));toast(t("created"));}setShowF(false);}
  function doDelete(){setEmps(emps.filter(function(e){return e.id!==delE.id;}));setDelE(null);toast(t("deleted"));}
  function doExport(){showExport("employees.csv",buildCSV(["Name","Nationality","Dept","Role","Salary","Allowances"],emps.map(function(e){return[e.nameEn,e.nat,e.dept,e.roleEn,e.salary,e.allow];})),"csv");}
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("employees")} <span style={{fontSize:14,color:C.mut,fontWeight:400}}>({emps.length})</span></h2><div style={{display:"flex",gap:8}}><Btn v="secondary" s="sm" onClick={doExport}><Ic d={icons.dl} s={14}/> {t("export")}</Btn><Btn onClick={function(){setForm(empty);setEditE(null);setShowF(true);}}><Ic d={icons.plus} s={14} c="#fff"/> {t("addEmp")}</Btn></div></div>
    <Modal open={showF} onClose={function(){setShowF(false);}} title={editE?t("editEmp"):t("addEmp")} wide><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:12}}><Inp label={t("nameAr")} value={form.name} onChange={function(v){setForm(Object.assign({},form,{name:v}));}}/><Inp label={t("nameEn")} value={form.nameEn} onChange={function(v){setForm(Object.assign({},form,{nameEn:v}));}}/><Sel label={t("nationality")} value={form.nat} onChange={function(v){setForm(Object.assign({},form,{nat:v}));}} options={[{v:"Omani",l:"Omani"},{v:"Indian",l:"Indian"},{v:"Pakistani",l:"Pakistani"},{v:"Egyptian",l:"Egyptian"},{v:"Other",l:"Other"}]}/><Sel label={t("department")} value={form.dept} onChange={function(v){setForm(Object.assign({},form,{dept:v}));}} options={DEPTS.map(function(d){return{v:d,l:d};})}/><Inp label={t("role")} value={form.roleEn} onChange={function(v){setForm(Object.assign({},form,{roleEn:v}));}}/><Inp label={t("salary")} type="number" value={form.salary} onChange={function(v){setForm(Object.assign({},form,{salary:Number(v)}));}}/><Inp label={t("allowances")} type="number" value={form.allow} onChange={function(v){setForm(Object.assign({},form,{allow:Number(v)}));}}/><Inp label={t("email")} value={form.email} onChange={function(v){setForm(Object.assign({},form,{email:v}));}}/></div><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:16}}><Btn v="ghost" onClick={function(){setShowF(false);}}>{t("cancel")}</Btn><Btn onClick={doSave}>{t("save")}</Btn></div></Modal>
    <Modal open={!!delE} onClose={function(){setDelE(null);}} title={t("confirmDel")}><p style={{color:C.mut,marginBottom:20}}>{delE?delE.nameEn:""}</p><div style={{display:"flex",justifyContent:"flex-end",gap:8}}><Btn v="ghost" onClick={function(){setDelE(null);}}>{t("cancel")}</Btn><Btn v="danger" onClick={doDelete}>{t("confirm")}</Btn></div></Modal>
    <Tbl cols={[{key:"name",label:t("name"),render:function(r){return <span style={{fontWeight:500}}>{r.nameEn}<br/><span style={{fontSize:11,color:C.mut}}>{r.name}</span></span>;}},{key:"nat",label:t("nationality"),render:function(r){return <Badge color={r.nat==="Omani"?"g":"y"}>{r.nat}</Badge>;}},{key:"dept",label:t("department")},{key:"role",label:t("role"),render:function(r){return r.roleEn;}},{key:"salary",label:t("salary"),render:function(r){return fmt(r.salary);}},{key:"join",label:t("joinDate"),render:function(r){return fD(r.join);}},{key:"act",label:"",render:function(r){return <div style={{display:"flex",gap:4}}><Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();setForm(Object.assign({},r));setEditE(r);setShowF(true);}}><Ic d={icons.edit} s={14}/></Btn><Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();setDelE(r);}}><Ic d={icons.trash} s={14} c={C.r}/></Btn></div>;}}]} data={emps}/></div>;}

function PayPage(p){var t=p.t,emps=p.emps,toast=p.toast,co=p.co,showExport=p.showExport;
  var [ran,setRan]=useState(false),[slip,setSlip]=useState(null);
  var pd=emps.map(function(e){var b=e.salary,a=e.allow,g=b+a,se=e.nat==="Omani"?b*SPF_EE:0;return Object.assign({},e,{basic:b,al:a,gross:g,spfE:se,net:g-se});});
  var tot=pd.reduce(function(s,e){return{b:s.b+e.basic,a:s.a+e.al,g:s.g+e.gross,s:s.s+e.spfE,n:s.n+e.net};},{b:0,a:0,g:0,s:0,n:0});
  function doExport(){showExport("payroll.csv",buildCSV(["Name","Basic","Allowances","Gross","SPF Employee","Net Pay"],pd.map(function(e){return[e.nameEn,e.basic,e.al,e.gross,e.spfE.toFixed(3),e.net.toFixed(3)];})),"csv");}
  if(slip) return <div><Btn v="ghost" s="sm" onClick={function(){setSlip(null);}} style={{marginBottom:16}}>{t("back")}</Btn>
    <div style={{background:"#fff",color:"#111",borderRadius:14,padding:36,maxWidth:700,margin:"0 auto"}}><div style={{textAlign:"center",borderBottom:"3px solid #c44530",paddingBottom:16,marginBottom:20}}><div style={{fontSize:20,fontWeight:800,color:"#c44530"}}>{co.nameAr}</div><div style={{fontSize:14,fontWeight:700,marginTop:10}}>{t("payslipTitle")}</div></div><div style={{fontSize:14,fontWeight:600,marginBottom:16}}>{slip.nameEn} — {slip.dept} — {slip.roleEn}</div><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,marginBottom:16}}><tbody><tr style={{borderBottom:"1px solid #eee"}}><td style={{padding:10}}>{t("basic")}</td><td style={{padding:10,textAlign:"right"}}>{fmt(slip.basic)}</td></tr><tr style={{borderBottom:"1px solid #eee"}}><td style={{padding:10}}>{t("allowances")}</td><td style={{padding:10,textAlign:"right"}}>{fmt(slip.al)}</td></tr><tr style={{background:"#f8f8f8",fontWeight:600}}><td style={{padding:10}}>Gross</td><td style={{padding:10,textAlign:"right"}}>{fmt(slip.gross)}</td></tr><tr><td style={{padding:10,color:"#ef4444"}}>{t("spfDed")} 7%</td><td style={{padding:10,textAlign:"right",color:"#ef4444"}}>-{fmt(slip.spfE)}</td></tr></tbody></table><div style={{display:"flex",justifyContent:"space-between",padding:14,background:"#c44530",borderRadius:8,color:"#fff"}}><span style={{fontSize:16,fontWeight:700}}>{t("netPay")}</span><span style={{fontSize:20,fontWeight:800}}>{fmt(slip.net)}</span></div></div></div>;
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("payrollMod")}</h2><div style={{display:"flex",gap:8}}><Btn v="secondary" onClick={doExport}><Ic d={icons.dl} s={14}/> {t("export")}</Btn><Btn onClick={function(){setRan(true);toast(t("payrollDone"));}} disabled={ran}>{ran?"✓ Done":t("runPayroll")}</Btn></div></div>
    <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.dollar} label={t("basic")} value={fmt(tot.b)} color={C.b}/><SC icon={icons.card} label={t("allowances")} value={fmt(tot.a)} color={C.g}/><SC icon={icons.shield} label={t("spfDed")} value={fmt(tot.s)} color={C.gld}/><SC icon={icons.wallet} label={t("netPay")} value={fmt(tot.n)} color={C.acc}/></div>
    <Tbl cols={[{key:"name",label:t("name"),render:function(r){return <span style={{fontWeight:500}}>{r.nameEn}</span>;}},{key:"dept",label:t("department")},{key:"basic",label:t("basic"),render:function(r){return fmt(r.basic);}},{key:"gross",label:"Gross",render:function(r){return <strong>{fmt(r.gross)}</strong>;}},{key:"spf",label:t("spfDed"),render:function(r){return r.nat==="Omani"?<span style={{color:C.r}}>-{fmt(r.spfE)}</span>:"—";}},{key:"net",label:t("netPay"),render:function(r){return <strong style={{color:C.g}}>{fmt(r.net)}</strong>;}},{key:"a",label:"",render:function(r){return <Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();setSlip(r);}}><Ic d={icons.eye} s={14}/> {t("payslip")}</Btn>;}}]} data={pd}/></div>;}

function ExpPage(p){var t=p.t,exps=p.exps,setExps=p.setExps,toast=p.toast,showExport=p.showExport;
  var [showA,setShowA]=useState(false);var cats=["rent","utilities","supplies","insurance","otherExp"];var [form,setForm]=useState({descEn:"",amount:0,cat:"utilities",vendor:"",vatI:false});
  function doAdd(){if(!form.descEn){toast("Required","e");return;}setExps(exps.concat([Object.assign({},form,{id:maxId(exps)+1,amount:Number(form.amount),date:today()})]));setShowA(false);setForm({descEn:"",amount:0,cat:"utilities",vendor:"",vatI:false});toast(t("created"));}
  function doDel(id){setExps(exps.filter(function(e){return e.id!==id;}));toast(t("deleted"));}
  function doExport(){showExport("expenses.csv",buildCSV(["Description","Amount","Category","Vendor","Date","VAT Incl"],exps.map(function(e){return[e.descEn,e.amount,e.cat,e.vendor,e.date,e.vatI?"Yes":"No"];})),"csv");}
  var totalExp=exps.reduce(function(s,e){return s+e.amount;},0);var inputVAT=exps.filter(function(e){return e.vatI;}).reduce(function(s,e){return s+(e.amount/1.05)*0.05;},0);
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("expenses")}</h2><div style={{display:"flex",gap:8}}><Btn v="secondary" s="sm" onClick={doExport}><Ic d={icons.dl} s={14}/> {t("export")}</Btn><Btn onClick={function(){setShowA(true);}}><Ic d={icons.plus} s={14} c="#fff"/> {t("addExp")}</Btn></div></div>
    <div style={{display:"flex",gap:14,marginBottom:24}}><SC icon={icons.wallet} label={t("expenses")} value={fmt(totalExp)} color={C.acc}/><SC icon={icons.dollar} label={t("inputVAT")} value={fmt(inputVAT)} sub={t("deductible")} color={C.b}/></div>
    <Modal open={showA} onClose={function(){setShowA(false);}} title={t("addExp")}><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Inp label="Description" value={form.descEn} onChange={function(v){setForm(Object.assign({},form,{descEn:v}));}}/><Inp label={t("amount")} type="number" value={form.amount} onChange={function(v){setForm(Object.assign({},form,{amount:v}));}}/><Sel label={t("category")} value={form.cat} onChange={function(v){setForm(Object.assign({},form,{cat:v}));}} options={cats.map(function(c){return{v:c,l:t(c)};})}/><Inp label={t("vendor")} value={form.vendor} onChange={function(v){setForm(Object.assign({},form,{vendor:v}));}}/></div><label style={{display:"flex",alignItems:"center",gap:8,marginTop:12,fontSize:13,color:C.txt,cursor:"pointer"}}><input type="checkbox" checked={form.vatI} onChange={function(e){setForm(Object.assign({},form,{vatI:e.target.checked}));}}/>{t("vatInc")}</label><div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:16}}><Btn v="ghost" onClick={function(){setShowA(false);}}>{t("cancel")}</Btn><Btn onClick={doAdd}>{t("save")}</Btn></div></Modal>
    <Tbl cols={[{key:"d",label:"Description",render:function(r){return r.descEn;}},{key:"amount",label:t("amount"),render:function(r){return <strong>{fmt(r.amount)}</strong>;}},{key:"cat",label:t("category"),render:function(r){return <Badge color="b">{t(r.cat)}</Badge>;}},{key:"vendor",label:t("vendor")},{key:"date",label:t("date"),render:function(r){return fD(r.date);}},{key:"a",label:"",render:function(r){return <Btn v="ghost" s="sm" onClick={function(e){e.stopPropagation();doDel(r.id);}}><Ic d={icons.trash} s={14} c={C.r}/></Btn>;}}]} data={exps}/></div>;}

function VATPage(p){var t=p.t,invs=p.invs,exps=p.exps,toast=p.toast,showExport=p.showExport;
  var [ck,setCk]=useState({reg:true,inv:true,ret:false,pay:false,rec:true});
  var oV=invs.reduce(function(s,i){return s+iVat(i);},0);var iV=exps.filter(function(e){return e.vatI;}).reduce(function(s,e){return s+(e.amount/1.05)*0.05;},0);var net=oV-iV;
  return <div><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:"0 0 20px"}}>{t("vatComp")}</h2>
    <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.dollar} label={t("outputVAT")} value={fmt(oV)} color={C.acc}/><SC icon={icons.dollar} label={t("inputVAT")} value={fmt(iV)} color={C.b}/><SC icon={icons.dollar} label={t("netVAT")} value={fmt(net)} color={net>0?C.r:C.g}/></div>
    <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24,marginBottom:20}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:16}}>{t("vatReturn")}</h3>
      {[{l:t("taxableSales"),v:fmt(oV/VAT)},{l:t("outputVAT")+" 5%",v:fmt(oV),h:true},{l:t("deductible"),v:fmt(iV)},{l:t("netPayable"),v:fmt(net),h:true,b:true}].map(function(r,i){return <div key={i} style={{display:"flex",justifyContent:"space-between",padding:"11px 14px",background:r.h?C.accG:i%2===0?C.hov:"transparent",borderRadius:6,marginBottom:2}}><span style={{fontSize:13,color:C.txt,fontWeight:r.b?700:400}}>{r.l}</span><span style={{fontSize:r.b?16:14,fontWeight:r.b?800:600,color:r.b?C.acc:C.txt}}>{r.v}</span></div>;})}
      <div style={{display:"flex",gap:8,marginTop:18}}>
        <Btn onClick={function(){showExport("vat-return.json",buildJSON({period:"Q1-2025",taxableSales:(oV/VAT).toFixed(3),outputVAT:oV.toFixed(3),inputVAT:iV.toFixed(3),netPayable:net.toFixed(3)}),"json");}}><Ic d={icons.dl} s={14} c="#fff"/> {t("download")}</Btn>
        <Btn v="secondary" onClick={function(){setCk(Object.assign({},ck,{ret:true}));toast(t("submitted"));}} disabled={ck.ret}>{ck.ret?"✓ "+t("submitted"):t("submit")}</Btn>
        {ck.ret&&!ck.pay&&<Btn v="success" onClick={function(){setCk(Object.assign({},ck,{pay:true}));toast(t("ok"));}}>{t("payDone")}</Btn>}
      </div></div>
    <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:14}}>{t("checklist")}</h3>
      {[{k:"reg",l:t("taxReg")},{k:"inv",l:t("invOk")},{k:"ret",l:t("retFiled")},{k:"pay",l:t("payDone")},{k:"rec",l:t("recsKept")}].map(function(item,i){return <div key={i} onClick={function(){var u={};u[item.k]=!ck[item.k];setCk(Object.assign({},ck,u));}} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<4?"1px solid "+C.brd:"none",cursor:"pointer"}}><div style={{width:22,height:22,borderRadius:6,display:"flex",alignItems:"center",justifyContent:"center",background:ck[item.k]?C.gB:C.hov,border:"1px solid "+(ck[item.k]?C.gD:C.brd)}}>{ck[item.k]&&<Ic d={icons.check} s={12} c={C.g}/>}</div><span style={{fontSize:13,color:ck[item.k]?C.txt:C.mut}}>{item.l}</span></div>;})}</div></div>;}

function SPFPage(p){var t=p.t,emps=p.emps,toast=p.toast,showExport=p.showExport;
  var [sub,setSub]=useState(false);var om=emps.filter(function(e){return e.nat==="Omani";});var ts=om.reduce(function(s,e){return s+e.salary;},0);var er=ts*SPF_ER,ee=ts*SPF_EE,gv=ts*SPF_GV;
  return <div><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:"0 0 20px"}}>{t("spf")}</h2>
    <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.shield} label={t("erContrib")} value={fmt(er)} sub={(SPF_ER*100).toFixed(2)+"%"} color={C.acc}/><SC icon={icons.shield} label={t("eeContrib")} value={fmt(ee)} sub={SPF_EE*100+"%"} color={C.b}/><SC icon={icons.shield} label={t("gvContrib")} value={fmt(gv)} sub={(SPF_GV*100).toFixed(2)+"%"} color={C.g}/><SC icon={icons.shield} label={t("monthlyTotal")} value={fmt(er+ee+gv)} sub={om.length+" "+t("eligible")} color={C.gld}/></div>
    <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}>
      <div style={{display:"flex",height:32,borderRadius:8,overflow:"hidden",marginBottom:18}}>{[[SPF_ER,C.acc,t("employer")],[SPF_EE,C.b,t("employee")],[SPF_GV,C.g,t("govt")]].map(function(a){return <div key={a[2]} style={{width:(a[0]/(SPF_ER+SPF_EE+SPF_GV))*100+"%",background:a[1],display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,color:"#fff",fontWeight:600}}>{a[2]} {(a[0]*100).toFixed(1)}%</div>;})}</div>
      <Tbl cols={[{key:"n",label:t("name"),render:function(r){return <span style={{fontWeight:500}}>{r.nameEn}</span>;}},{key:"spf",label:t("spfNo")},{key:"s",label:t("basicSal"),render:function(r){return fmt(r.salary);}},{key:"er",label:t("erShare"),render:function(r){return fmt(r.salary*SPF_ER);}},{key:"ee",label:t("eeShare"),render:function(r){return fmt(r.salary*SPF_EE);}},{key:"tot",label:t("totalCont"),render:function(r){return <strong>{fmt(r.salary*(SPF_ER+SPF_EE))}</strong>;}}]} data={om}/>
      <div style={{display:"flex",gap:8,marginTop:18}}>
        <Btn onClick={function(){showExport("spf-report.csv",buildCSV(["Name","SPF#","Salary","Employer 11.75%","Employee 7%","Total"],om.map(function(e){return[e.nameEn,e.spf,e.salary,(e.salary*SPF_ER).toFixed(3),(e.salary*SPF_EE).toFixed(3),(e.salary*(SPF_ER+SPF_EE)).toFixed(3)];})),"csv");}}><Ic d={icons.dl} s={14} c="#fff"/> {t("dlSPF")}</Btn>
        <Btn v="secondary" onClick={function(){setSub(true);toast(t("submitted"));}} disabled={sub}>{sub?"✓ "+t("submitted"):t("submitSPF")}</Btn>
      </div></div></div>;}

function OmanPage(p){var t=p.t,emps=p.emps,toast=p.toast,showExport=p.showExport;
  var depts=useMemo(function(){var m={};emps.forEach(function(e){if(!m[e.dept])m[e.dept]={t:0,o:0};m[e.dept].t++;if(e.nat==="Omani")m[e.dept].o++;});return Object.entries(m).map(function(en){return{dept:en[0],t:en[1].t,o:en[1].o,pct:Math.round(en[1].o/en[1].t*100),target:TARGETS[en[0]]||20};});},[emps]);
  var totalO=emps.filter(function(e){return e.nat==="Omani";}).length;var ok=depts.filter(function(d){return d.pct>=d.target;}).length;
  function doExport(){showExport("omanization.csv",buildCSV(["Department","Total","Omani","Current%","Target%","Compliant","Gap"],depts.map(function(d){return[d.dept,d.t,d.o,d.pct,d.target,d.pct>=d.target?"Yes":"No",Math.max(0,Math.ceil(d.target/100*d.t)-d.o)];})),"csv");}
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("oman")}</h2><Btn v="secondary" onClick={doExport}><Ic d={icons.dl} s={14}/> {t("omanReport")}</Btn></div>
    <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.flag} label={t("overallRate")} value={Math.round(totalO/emps.length*100)+"%"} sub={totalO+"/"+emps.length} color={C.acc}/><SC icon={icons.check} label={t("compliant")} value={ok} color={C.g}/><SC icon={icons.alert} label={t("nonComp")} value={depts.length-ok} color={C.r}/></div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:14}}>{depts.map(function(d){var met=d.pct>=d.target,gap=Math.max(0,Math.ceil(d.target/100*d.t)-d.o);return <div key={d.dept} style={{background:C.card,border:"1px solid "+(met?C.gD:C.rD),borderRadius:14,padding:18,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,right:0,padding:"3px 10px",borderRadius:"0 14px 0 10px",background:met?C.gB:C.rB,fontSize:10,fontWeight:700,color:met?C.g:C.r}}>{met?t("compliant"):t("actionNeeded")}</div><h4 style={{fontSize:14,fontWeight:700,color:C.txt,marginBottom:10}}>{d.dept}</h4><div style={{display:"flex",justifyContent:"space-between",marginBottom:6,fontSize:12}}><span style={{color:C.mut}}>{t("current")}: <strong style={{color:C.txt}}>{d.pct}%</strong></span><span style={{color:C.mut}}>{t("target")}: <strong style={{color:met?C.g:C.r}}>{d.target}%</strong></span></div><PBar value={d.pct} max={d.target} color={met?C.g:C.r} h={10}/><div style={{marginTop:10,display:"flex",gap:12,fontSize:12,color:C.mut}}><span>{t("omani")}: <strong style={{color:C.g}}>{d.o}</strong></span><span>{t("expat")}: <strong style={{color:C.y}}>{d.t-d.o}</strong></span></div>{!met&&<div style={{marginTop:10,padding:"7px 10px",background:C.rB,borderRadius:8,border:"1px solid "+C.rD,fontSize:11,color:C.r}}>⚠ {t("needHire")} {gap} {t("moreOmanis")}</div>}</div>;})}</div></div>;}

function RepPage(p){var t=p.t,invs=p.invs,emps=p.emps,exps=p.exps,toast=p.toast,showExport=p.showExport;
  var inc=invs.filter(function(i){return i.status==="paid";}).reduce(function(s,i){return s+iTotal(i);},0);var pay=emps.reduce(function(s,e){return s+e.salary+e.allow;},0);var spfC=emps.filter(function(e){return e.nat==="Omani";}).reduce(function(s,e){return s+e.salary*SPF_ER;},0);var expA=exps.reduce(function(s,e){return s+e.amount;},0);var costs=pay+spfC+expA,np=inc-costs,mg=inc>0?((np/inc)*100).toFixed(1):"0";
  function doExport(){showExport("profit-loss.csv",buildCSV(["Item","Amount OMR"],[["Revenue (Paid)",inc.toFixed(3)],["Payroll",pay.toFixed(3)],["SPF Employer",spfC.toFixed(3)],["Operating Expenses",expA.toFixed(3)],["Total Costs",costs.toFixed(3)],["Net Profit",np.toFixed(3)],["Margin %",mg]]),"csv");}
  var rows=[{l:t("revenue")+" ("+t("paid")+")",v:inc,c:C.g,b:true},{l:"— "+t("payroll"),v:-pay,c:C.r},{l:"— "+t("spf"),v:-spfC,c:C.r},{l:"— "+t("expenses"),v:-expA,c:C.r},{l:t("totalExp"),v:-costs,c:C.r,b:true},{l:t("netProfit"),v:np,c:np>=0?C.g:C.r,b:true,a:true}];
  return <div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:0}}>{t("reports")}</h2><Btn onClick={doExport}><Ic d={icons.dl} s={14} c="#fff"/> {t("export")}</Btn></div>
    <div style={{display:"flex",gap:14,flexWrap:"wrap",marginBottom:24}}><SC icon={icons.chart} label={t("totalIncome")} value={fmt(inc)} color={C.g}/><SC icon={icons.wallet} label={t("totalExp")} value={fmt(costs)} color={C.r}/><SC icon={icons.dollar} label={t("netProfit")} value={fmt(np)} color={np>=0?C.g:C.r}/><SC icon={icons.pie} label={t("grossMargin")} value={mg+"%"} color={C.gld}/></div>
    <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:16}}>{t("incomeStatement")}</h3>{rows.map(function(r,i){return <div key={i} style={{display:"flex",justifyContent:"space-between",padding:"12px 14px",background:r.a?C.accG:i%2===0?C.hov:"transparent",borderRadius:6,marginBottom:2,borderTop:r.a?"2px solid "+C.acc:"none",marginTop:r.a?8:0}}><span style={{fontSize:13,color:C.txt,fontWeight:r.b?700:400}}>{r.l}</span><span style={{fontSize:r.a?18:14,fontWeight:r.b?800:600,color:r.c}}>{r.v<0?"−":""}{fmt(Math.abs(r.v))}</span></div>;})}</div></div>;}

function SetPage(p){var t=p.t,co=p.co,setCo=p.setCo,toast=p.toast,showExport=p.showExport;var [form,setForm]=useState(co);
  return <div><h2 style={{fontSize:22,fontWeight:700,color:C.txt,margin:"0 0 20px"}}>{t("settings")}</h2>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}>
      <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:16}}>Company Info</h3><div style={{display:"flex",flexDirection:"column",gap:12}}><Inp label={t("compName")} value={form.nameAr} onChange={function(v){setForm(Object.assign({},form,{nameAr:v}));}}/><Inp label={t("compNameEn")} value={form.nameEn} onChange={function(v){setForm(Object.assign({},form,{nameEn:v}));}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Inp label={t("crNo")} value={form.cr} onChange={function(v){setForm(Object.assign({},form,{cr:v}));}}/><Inp label={t("taxId")} value={form.taxId} onChange={function(v){setForm(Object.assign({},form,{taxId:v}));}}/></div><Inp label={t("address")} value={form.address} onChange={function(v){setForm(Object.assign({},form,{address:v}));}}/><Inp label={t("email")} value={form.email} onChange={function(v){setForm(Object.assign({},form,{email:v}));}}/></div><Btn onClick={function(){setCo(form);toast(t("ok"));}} style={{marginTop:18}}><Ic d={icons.check} s={14} c="#fff"/> {t("saveSettings")}</Btn></div>
      <div style={{display:"flex",flexDirection:"column",gap:16}}>
        <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:16}}>{t("language")}</h3><div style={{display:"flex",gap:10}}>{[["ar","العربية 🇴🇲"],["en","English 🇬🇧"]].map(function(a){return <button key={a[0]} type="button" onClick={function(){p.setLang(a[0]);}} style={{flex:1,padding:14,borderRadius:10,border:"2px solid "+(p.lang===a[0]?C.acc:C.brd),background:p.lang===a[0]?C.accG:C.hov,color:p.lang===a[0]?C.acc:C.txt,fontSize:14,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>{a[1]}</button>;})}</div></div>
        <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24}}><h3 style={{fontSize:15,fontWeight:700,color:C.txt,marginBottom:16}}>Data Export</h3><div style={{display:"flex",flexDirection:"column",gap:8}}>
          <Btn v="secondary" onClick={function(){showExport("erp-backup.json",buildJSON({employees:p.emps,invoices:p.invs,expenses:p.exps,settings:form}),"json");}} style={{width:"100%"}}><Ic d={icons.dl} s={14}/> Export All (JSON)</Btn>
          <Btn v="secondary" onClick={function(){showExport("employees.csv",buildCSV(["Name","Dept","Salary","Nationality"],p.emps.map(function(e){return[e.nameEn,e.dept,e.salary,e.nat];})),"csv");}} style={{width:"100%"}}><Ic d={icons.users} s={14}/> Employees CSV</Btn>
          <Btn v="secondary" onClick={function(){showExport("invoices.csv",buildCSV(["ID","Client","Total","Status"],p.invs.map(function(i){return[i.id,i.clientEn,iGrand(i).toFixed(3),i.status];})),"csv");}} style={{width:"100%"}}><Ic d={icons.file} s={14}/> Invoices CSV</Btn>
        </div></div>
        <div style={{background:C.card,border:"1px solid "+C.brd,borderRadius:14,padding:24,fontSize:12,color:C.mut,lineHeight:1.8}}>v1.0 | VAT 5% | SPF: ER {(SPF_ER*100).toFixed(2)}% + EE {SPF_EE*100}% + Govt {(SPF_GV*100).toFixed(2)}% | OMR 3dp</div>
      </div>
    </div></div>;}
